const SHOULD_DEEP_SCAN_ROUTES: boolean = true;
const SHOULD_DISPLAY_REQUEST_DURATION: boolean = true;
const OPERATIONS_SORTER: string = "alpha";
const TAGS_SORTER: string = "alpha";

const CONFIG_SWAGGER_CONSTANT: {
	OPERATIONS_SORTER: string;
	SHOULD_DEEP_SCAN_ROUTES: boolean;
	SHOULD_DISPLAY_REQUEST_DURATION: boolean;
	TAGS_SORTER: string;
} = {
	OPERATIONS_SORTER,
	SHOULD_DEEP_SCAN_ROUTES,
	SHOULD_DISPLAY_REQUEST_DURATION,
	TAGS_SORTER,
};

export default CONFIG_SWAGGER_CONSTANT;
